# Generated by Django 3.2 on 2025-05-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('HEM', 'Hembra'), ('MAC', 'Macho')], default='MAC', max_length=3)),
                ('vacuna', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=3)),
                ('desparacitado', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=3)),
                ('estado', models.CharField(choices=[('ADP', 'Adoptado'), ('EAD', 'En Adopción')], default='EAD', max_length=3)),
                ('castrado', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=3)),
                ('caracteristicas', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='mascotas/')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
